# Generated by Django 3.2 on 2020-12-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_consumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchesspacex',
            name='launch_site',
        ),
        migrations.RemoveField(
            model_name='launchesspacex',
            name='launch_success',
        ),
        migrations.RemoveField(
            model_name='launchesspacex',
            name='rocket_name',
        ),
        migrations.RemoveField(
            model_name='launchesspacex',
            name='upcoming',
        ),
        migrations.RemoveField(
            model_name='launchesspacex',
            name='yt_video_link',
        ),
    ]
